prevent JIT compiler to cleanup `this` in some Webkit Versions
fixes:
TypeError: 'undefined' is not an object (evaluating 'this.map = map')  (line 723 in require.js)